server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: POSTCODE-SERVICE
          uri: lb://POSTCODE-SERVICE
          predicates:
            - Path=/postcode/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost